
--- SQL code to create the AccountMove table
--- This table is designed to store information about account moves
CREATE TABLE AccountMove (
    is_move_sent BIT,
    create_date DATETIME,
    write_date DATETIME,
    extract_status_code NVARCHAR(255),
    extract_remote_id INT,
    extract_attachment_id INT,
    stock_move_id INT,
    transfer_model_id INT,
    tax_closing_end_date DATETIME,
    tax_report_control_error NVARCHAR(255),
    campaign_id INT,
    source_id INT,
    medium_id NVARCHAR(255),
    team_id INT,
    asset_id INT,
    asset_number_days INT,
    asset_depreciation_beginning_date DATETIME,
    depreciation_value DECIMAL(18, 2),
    asset_value_change DECIMAL(18, 2),
    suspense_statement_line_id INT,
    force_release_to_pay NVARCHAR(255),
    auto_invoice_id INT,
    auto_generated BIT,
    exchange_rate DECIMAL(18, 6),
    approver_id INT,
    amount_total DECIMAL(18, 2),
    amount_untaxed_signed DECIMAL(18, 2),
    amount_tax_signed DECIMAL(18, 2),
    amount_total_signed DECIMAL(18, 2),
    amount_total_in_currency_signed DECIMAL(18, 2),
    amount_residual_signed DECIMAL(18, 2),
    quick_edit_total_amount DECIMAL(18, 2),
    is_storno BIT,
    always_tax_exigible BIT,
    to_check NVARCHAR(255),
    posted_before NVARCHAR(255),
    write_uid INT,
    date NVARCHAR(255),
    auto_post_until DATETIME,
    invoice_date DATETIME,
    invoice_date_due DATETIME,
    amount_untaxed DECIMAL(18, 2),
    amount_tax DECIMAL(18, 2),
    amount_residual DECIMAL(18, 2),
    auto_post NVARCHAR(255),
    creator_id INT,
    debit_origin_id NVARCHAR(255),
    declaration NVARCHAR(255),
    company_name_id INT,
    cu_invoice_no NVARCHAR(255),
    release_to_pay_manual NVARCHAR(255),
    release_to_pay NVARCHAR(255),
    extract_state NVARCHAR(255),
    edi_state NVARCHAR(255),
    payment_state_before_switch NVARCHAR(255),
    narration NVARCHAR(255),
    invoice_origin NVARCHAR(255),
    invoice_partner_display_name NVARCHAR(255),
    invoice_source_email NVARCHAR(255),
    payment_state NVARCHAR(255),
    qr_code_method NVARCHAR(255),
    payment_reference NVARCHAR(255),
    inalterable_hash NVARCHAR(255),
    bank_id INT,
    payment_term_id NVARCHAR(255),
    sequence_prefix NVARCHAR(255),
    access_token NVARCHAR(255),
    name NVARCHAR(255),
    ref NVARCHAR(255),
    state NVARCHAR(255),
    move_type NVARCHAR(255),
    id INT PRIMARY KEY,
    sequence_number INT,
    message_main_attachment_id NVARCHAR(255),
    journal_id INT,
    company_id INT,
    payment_id INT,
    statement_line_id INT,
    tax_cash_basis_rec_id NVARCHAR(255),
    tax_cash_basis_origin_move_id NVARCHAR(255),
    auto_post_origin_id NVARCHAR(255),
    secure_sequence_number NVARCHAR(255),
    invoice_payment_term_id NVARCHAR(255),
    partner_id INT,
    commercial_partner_id NVARCHAR(255),
    partner_shipping_id NVARCHAR(255),
    partner_bank_id NVARCHAR(255),
    fiscal_position_id INT,
    currency_id INT,
    reversed_entry_id NVARCHAR(255),
    invoice_user_id INT,
    invoice_incoterm_id NVARCHAR(255),
    invoice_cash_rounding_id INT,
    create_uid INT
);






